### ISSUE TITLE
Step 10: Define & prioritize Extra features (Not required)

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#16]
**__Feature Description__**
After completing the MVP, we could add some of these features to the game :)
Prioritize between 3 features from the list below.

**__Extras (Not Required)__**
1. Implement the game to allow human-to-human competition between 2 players or human-vs-computer competition.
2. Allow the user to choose the color to be used to fill in the grid
3. Maintain player metrics across sessions for the last 3 games that have been played
4. Allow the user to specify the dimensions of the grid
5. Add a countdown timer showing time remaining in the game and create an input field to allow the user to set the starting number of minutes and seconds.
6. Animate the rolling of the dice
7. Play a sound to simulate the rolling dice
8. Add a graph to the leader board to show the number of times a number has been rolled
9. Support dark/light mode

**__Additional Considerations__**

Voted:

- Play a sound to simulate the rolling dice
- Animate the rolling of the dice 
- Support dark/light mode

**Comment by PaulaR-05** [comment]
**Favorite features are:** 

3. Maintain player metrics across sessions for the last 3 games that have been played
6. Animate the rolling of the dice
9. Support dark/light mode

**Comment by goodman2814** [comment]
Favorite Features are:
2. Allow the user to choose the color to be used to fill in the grid.
6. Animate the rolling of the dice.
7. Play a sound to simulate the rolling dice.

Runner-up is:
9. Support dark/light mode

**Comment by nazgul7d** [comment]
**Favorite features are:**
Animate the rolling of the dice
Play a sound to simulate the rolling dice
Support dark/light mode

**Comment by Foughty** [comment]
Here are my favs:
1) Implement the game to allow human-to-human competition between 2 players or human-vs-computer competition.
5) Add a countdown timer showing time remaining in the game and create an input field to allow the user to set the starting 
number of minutes and seconds.
9) Support dark/light mode
