### ISSUE TITLE
Acknowledgment List

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#62]
**__Feature Description__**
Every time we get help from somewhere, it's a good practice to give credit to the author on our README.MD file :)
So, let's keep this issue here, then we add the links from where we got some help. When it comes to writing our readme, it will help us to remember everyone xD

**__Additional Considerations__**
Your post should have the author, the link, and how to write it on README For example:

**Author:** Ksenia Kondrashova
**Link where you got help:** https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482 
**Acknowledgments:** Huge shout out to [Ksenia Kondrashova](https://github.com/uuuulala) for the Background Blob Animation that gives the illusion of blobs morphing randomly. [Step-by-Step Guide](https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482).

**Comment by PaulaR-05** [comment]
Author: Ksenia Kondrashova
Link where you got help: https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482
Acknowledgments: Huge shout out to [Ksenia Kondrashova](https://github.com/uuuulala) for the Background Blob Animation that gives the illusion of blobs morphing randomly. [Step-by-Step Guide](https://dev.to/uuuuuulala/making-background-blob-animation-in-just-15kb-step-by-step-guide-2482).

**Comment by goodman2814** [comment]
Author: George Whiting
Link: https://medium.com/@thewebdevg/creating-a-gameboard-with-css-grid-47da8ac25078
Acknowledgments: Thanks to George Whiting for his tutorial on making a grid for players.
